service: emojiTracker-mw-scripts
frameworkVersion: '3'
configValidationMode: warn

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev-27-june
  region: ap-south-1
  timeout: 30
  memorySize: 250
  iamManagedPolicies:
    - "arn:aws:iam::834534110091:policy/emojiTrackerDevLambda"
    - "arn:aws:iam::834534110091:policy/emojiTrackerDevS3Policy"
    
  vpc:
    securityGroupIds:
     -  sg-0fb7520ad9c549cff
    subnetIds:
      - subnet-076377af58b0204e9

package:
  individually: true

functions:
  aggregation_script:
    handler: apps/mw-app/src/app/lambda-ratings-aggregation.handler
    events:
      - schedule:
          rate: cron(5 0 * * ? *)
          timezone: Asia/Kolkata

custom:
  dotenv:
     exclude:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_REGION
      
  webpack:
    webpackConfig: 'webpack.config.js' # Name of webpack configuration file
    includeModules: true # Node modules configuration for packaging
    excludeFiles: src/**/*.test.js
    packagerOptions:
      scripts:
        - npm uninstall *
        - npm install sequelize@6.29.0
 
plugins:
  - serverless-local-schedule
  - serverless-dotenv-plugin
  - serverless-webpack

